spring:
  data:
    mongodb:
      database: utcn-forum
      uri: mongodb+srv://vexa:admin@cluster0.2qcbzhm.mongodb.net/?retryWrites=true&w=majority
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
